version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - echo Build started on `date`
  pre_build:
    commands:
      - php -v
      - which php
      - composer install --no-interaction
  build:
    commands:
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
